# basic options
title: Team GRIT blog
author: Owen McGonagle
email: mcgonagleo@gmail.com
description: A few stories from recent Zwift GRIT rides
twitter_username: mcgonagleo
github_username:  mcgonago

# Build settings
markdown: kramdown
theme: minima


